### ISSUE TITLE
Latest version of mp4parser

### ISSUE THREAD

**Issue by hiddeneyes02** [Tourenathan-G5organisation/SiliCompressor#67]
In my project I am also using the latest version of mp4parser:

> implementation 'com.googlecode.mp4parser:isoparser:1.1.21'

Which making the generated video has no sound. How to fix this please?

**Comment by MasoudBrain** [comment]
I'm also using the 1.1.21 version of isoparser in my project and when I build my project, the gradle gives an error: 'Duplicate zip error'. Because I have two isoparser library in my project (one that I myself defined and one for silicompressor). but I need both of them. So how to handle this problem?

**Comment by Tourenathan-G5organisation** [comment]
solved in v2.2.3
check
